[package]
name = "thread_pool"
version = "0.1.0"
edition = "2018"
authors = ["mrudisel"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aquire = { path="../aquire" }
num_cpus = "1.4"
